### ISSUE TITLE
Improvements & Bugs

### ISSUE THREAD

**Issue by c-seeger** [purefundev/flutter_cookie_consent#1]
Improvements:

- Please add this repository to https://pub.dev/packages/cookie_consent page, to provide users the opportunity to contribute to this project
- create a release tag to simplify `flutter pub get`

Bugs:
- The project is currently not building due to several errors.

```
../../../../../.pub-cache/hosted/pub.dev/modal_bottom_sheet-2.1.2/lib/src/material_with_modal_page_route.dart:4:1: Error:
'ModalBottomSheetRoute' is imported from both 'package:flutter/src/material/bottom_sheet.dart' and
'package:modal_bottom_sheet/src/bottom_sheet_route.dart'.
import '../modal_bottom_sheet.dart';
^^^^^^^^^^^^^^^^^^^^^
../../../../../.pub-cache/hosted/pub.dev/modal_bottom_sheet-2.1.2/lib/src/bottom_sheets/material_bottom_sheet.dart:28:13:
Error: 'ModalBottomSheetRoute' is imported from both 'package:flutter/src/material/bottom_sheet.dart' and
'package:modal_bottom_sheet/src/bottom_sheet_route.dart'.
      .push(ModalBottomSheetRoute<T>(
            ^^^^^^^^^^^^^^^^^^^^^
../../../../../.pub-cache/hosted/pub.dev/modal_bottom_sheet-2.1.2/lib/src/bottom_sheets/material_bottom_sheet.dart:50:10:
Error: A value of type 'Object?' can't be returned from an async function with return type 'Future<T?>'.
 - 'Object' is from 'dart:core'.
 - 'Future' is from 'dart:async'.
  return result;
         ^
../../../../../.pub-cache/hosted/pub.dev/modal_bottom_sheet-2.1.2/lib/src/bottom_sheets/bar_bottom_sheet.dart:102:13: Error:
'ModalBottomSheetRoute' is imported from both 'package:flutter/src/material/bottom_sheet.dart' and
'package:modal_bottom_sheet/src/bottom_sheet_route.dart'.
      .push(ModalBottomSheetRoute<T>(
            ^^^^^^^^^^^^^^^^^^^^^
../../../../../.pub-cache/hosted/pub.dev/modal_bottom_sheet-2.1.2/lib/src/bottom_sheets/bar_bottom_sheet.dart:125:10: Error: A
value of type 'Object?' can't be returned from an async function with return type 'Future<T?>'.
 - 'Object' is from 'dart:core'.
 - 'Future' is from 'dart:async'.
  return result;
         ^
Unhandled exception:
Unsupported operation: Unsupported invalid type InvalidType(<invalid>) (InvalidType).
#0      throwUnsupportedInvalidType (package:dev_compiler/src/kernel/kernel_helpers.dart:13)
#1      JSTypeRep.typeFor (package:dev_compiler/src/kernel/js_typerep.dart:83)
#2      ProgramCompiler._emitIsExpression (package:dev_compiler/src/kernel/compiler.dart:7309)
#3      ProgramCompiler.visitIsExpression (package:dev_compiler/src/kernel/compiler.dart:7296)
#4      IsExpression.accept (package:kernel/ast.dart:7496)
#5      ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:4611)
#6      ProgramCompiler._visitTest (package:dev_compiler/src/kernel/compiler.dart:4602)
#7      ProgramCompiler._visitTest.shortCircuit (package:dev_compiler/src/kernel/compiler.dart:4588)
#8      ProgramCompiler._visitTest (package:dev_compiler/src/kernel/compiler.dart:4593)
#9      ProgramCompiler.visitLogicalExpression (package:dev_compiler/src/kernel/compiler.dart:7200)
#10     LogicalExpression.accept (package:kernel/ast.dart:6866)
#11     ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:4611)
#12     ProgramCompiler.visitReturnStatement (package:dev_compiler/src/kernel/compiler.dart:5182)
#13     ReturnStatement.accept (package:kernel/ast.dart:10159)
#14     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:4520)
#15     MappedListIterable.elementAt (dart:_internal/iterable.dart:425)
#16     ListIterator.moveNext (dart:_internal/iterable.dart:354)
#17     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189)
#18     new _GrowableList.of (dart:core-patch/growable_array.dart:150)
#19     new List.of (dart:core-patch/array_patch.dart:39)
#20     SetBase.toList (dart:collection/set.dart:119)
#21     ProgramCompiler.visitBlock (package:dev_compiler/src/kernel/compiler.dart:4701)
#22     Block.accept (package:kernel/ast.dart:9195)
#23     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:4520)
#24     ProgramCompiler._emitFunctionScopedBody (package:dev_compiler/src/kernel/compiler.dart:4553)
#25     ProgramCompiler._emitSyncFunctionBody.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:4259)
#26     ProgramCompiler._withLetScope (package:dev_compiler/src/kernel/compiler.dart:2829)
#27     ProgramCompiler._withCurrentFunction (package:dev_compiler/src/kernel/compiler.dart:4296)
#28     ProgramCompiler._emitSyncFunctionBody (package:dev_compiler/src/kernel/compiler.dart:4255)
#29     ProgramCompiler._emitFunction (package:dev_compiler/src/kernel/compiler.dart:4060)
#30     ProgramCompiler._emitMethodDeclaration.<anonymous closure> (package:dev_compiler/src/kernel/compiler.dart:2392)
#31     ProgramCompiler._withMethodDeclarationContext (package:dev_compiler/src/kernel/compiler.dart:4323)
#32     ProgramCompiler._emitMethodDeclaration (package:dev_compiler/src/kernel/compiler.dart:2391)
#33     ProgramCompiler._emitClassMethods (package:dev_compiler/src/kernel/compiler.dart:2332)
#34     ProgramCompiler._emitClassDeclaration (package:dev_compiler/src/kernel/compiler.dart:932)
#35     ProgramCompiler._emitClass (package:dev_compiler/src/kernel/compiler.dart:846)
#36     List.forEach (dart:core-patch/growable_array.dart:416)
#37     ProgramCompiler._emitLibrary (package:dev_compiler/src/kernel/compiler.dart:784)
#38     List.forEach (dart:core-patch/growable_array.dart:416)
#39     ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:505)
#40     IncrementalJavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:223)
#41     FrontendCompiler.writeJavaScriptBundle (package:frontend_server/frontend_server.dart:794)
<asynchronous suspension>
#42     FrontendCompiler.recompileDelta (package:frontend_server/frontend_server.dart:959)
<asynchronous suspension>
#43     listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1381)
<asynchronous suspension>
the Dart compiler exited unexpectedly.
```

**Comment by jasminder** [comment]
Same Issue.

**Comment by jasminder** [comment]
You can add the following in pubspec.yaml to fix the build issue:
dependency_overrides:
   modal_bottom_sheet: ^3.0.0-pre
  
 However, we still need more customization options. Why are there static colors of white and black in code?
